### ISSUE TITLE
Делиться ключом при помощи qr кода

### ISSUE THREAD

**Issue by vivabelarus** [wrwrabbit/Partisan-SMS#11]

**Comment by SsNipeR1** [comment]
небезопасно

**Comment by vivabelarus** [comment]
> 
> 
> небезопасно

Чем небезопасно?

**Comment by SsNipeR1** [comment]
> > небезопасно
> 
> Чем небезопасно?

кто угодно может взять ваш телефон, например ОМОНовец и скопировать ваш ключ и получить доступ к чату

**Comment by vivabelarus** [comment]
> 
> 
> > > небезопасно
> > 
> > 
> > Чем небезопасно?
> 
> кто угодно может взять ваш телефон, например ОМОНовец и скопировать ваш ключ и получить доступ к чату

Во-первых, на данный момент он может просто взять телефон и посмотреть строку, соответствующую ключу. Поэтому qr, наверное, не особо опаснее будет. 

Во-вторых, сейчас есть скрытие ключей. Если его настроить, нельзя просто так зайти в настройки и подсмотреть ключ. Естественно, при угрозе применения силы он сможет получить доступ. Но от этого мы здесь не реализовывали защиту.

**Comment by vivabelarus** [comment]
Хотя... Можно сделать ключ одноразовым. Запретить его просмотр после настройки
