### ISSUE TITLE
Использовать асимметричное шифрование

### ISSUE THREAD

**Issue by Logarithmus** [wrwrabbit/Partisan-SMS#12]
Использование симметричного шифрования небезопасно, поскольку в случае получения доступа к одному из устройств злоумышленники смогут читать все переписки всех людей.

Предлагаю использовать алгоритм `ed25519`. Он есть в `libsodium`, к ней есть бинды для Kotlin.

**Comment by vivabelarus** [comment]
При использовании симметричного шифрования злоумышленник получит доступ к переписке между парой человек, которые используют один и тот же ключ. При использовании асимметричного шифрования злоумышленник сможет расшифровать только входящие сообщения. Поэтому, на сколько я понимаю, асимметричное шифрование безопаснее, но не на много. Его имеет смысл использовать скорее для безопасного обмена ключами, чем непосредственно для шифрования.

**Comment by Logarithmus** [comment]
>Поэтому, на сколько я понимаю, асимметричное шифрование безопаснее, но не на много. Его имеет смысл использовать скорее для безопасного обмена ключами, чем непосредственно для шифрования.

Насколько мне известно, ssh именно так и работает: обмен ключами асимметричными ed25519/rsa, затем шифрование данных симметричным chacha20-poly1305 или AES.

**Comment by SsNipeR1** [comment]
> Использование симметричного шифрования небезопасно, поскольку в случае получения доступа к одному из устройств злоумышленники смогут читать все переписки всех людей.
> 
> Предлагаю использовать алгоритм `ed25519`. Он есть в `libsodium`, к ней есть бинды для Kotlin.

есть OpenPGP зачем

**Comment by vivabelarus** [comment]
> 
> 
> > Использование симметричного шифрования небезопасно, поскольку в случае получения доступа к одному из устройств злоумышленники смогут читать все переписки всех людей.
> > Предлагаю использовать алгоритм `ed25519`. Он есть в `libsodium`, к ней есть бинды для Kotlin.
> 
> есть OpenPGP зачем

Вообще тут вся проблема в том, что мы шифруем смс, а это накладывает определённые ограничения. Стандартные протоколы могут сильно увеличивать размер передаваемыех данных, количество смс, что не желательно. Не знаю, на сколько нужно париться об этом, но раз уж был сделан некоторый упор на небольшой размер, будем этого придерживаться.

**Comment by vivabelarus** [comment]
Асимметричное шифрование не будет использоваться из-за уязвимости к Man in the middle.

**Comment by emmatebibyte** [comment]
> Асимметричное шифрование не будет использоваться из-за уязвимости к Man in the middle.

but symmetric encryption is vulnerable to the same man in the middle attack, no? you're just sending the private key across sms, so any party watching your messages (like the phone service provider) can see it.

**Comment by emmatebibyte** [comment]
understood
