### ISSUE TITLE
Запретить слабые ключи шифрования

### ISSUE THREAD

**Issue by vivabelarus** [wrwrabbit/Partisan-SMS#13]

**Comment by SsNipeR1** [comment]
типа запретить менее 3192 бит?

**Comment by vivabelarus** [comment]
> 
> 
> типа запретить менее 3192 бит?

Сейчас используется симметричное шифрование. Ключ фактически генерируется из пароля. Соответсвенно, запретить слабые пароли. Ну стандартные проверки на то, чтобы были символы в разных регистрах, цифры, вот это вот всё.

**Comment by vivabelarus** [comment]
Вместо старой генерации ключа по паролю сейчас будем генерировать полноценные 256-битные ключи
