### ISSUE TITLE
Possibility to disable sending encrypted SMS

### ISSUE THREAD

**Issue by garret** [wrwrabbit/Partisan-SMS#35]
I don't know if it just me who hasn't got the spirit of the app but is there a way to also send unencrypted messages, so just normal SMS and possibly set this behavior as default as well?

**Comment by ceptonit** [comment]
> I don't know if it just me who hasn't got the spirit of the app but is there a way to also send unencrypted messages, so just normal SMS and possibly set this behavior as default as well?

You actually can if you don't set a Global Encryption Key. Just hit the cancel button when the popup comes up asking you to set an encryption key.

But yes, it would be nice to have the choice of encrypting or not, thus removing this encryption popup.

**Comment by garret** [comment]
I don't know, would it be better to tag this issue as an "enhancement" so maybe at some point if it is implemented it can be closed?

**Comment by vivabelarus** [comment]
> I don't know, would it be better to tag this issue as an "enhancement" so maybe at some point if it is implemented it can be closed?

We will implement it. Don't worry :)

**Comment by tiagocasalribeiro** [comment]
It would also be good to disable the Global Encryption Key popup, for a per user key usage, as it is annoying in that use case.
It is also bad when the Global Encryption Key is set that all sms sent will be encrypted, even for people I haven't exchanged keys with.
Maybe you could implement a short prefix to the sms sent so the app on the receiver side can identify it is encrypted and apply the keys and enable the encryption/decryption accordingly.

**Comment by vivabelarus** [comment]
Disabling encryption is implemented in 4.0.0.
Annoying global key popup replaced with less annoying snackbar.
https://github.com/wrwrabbit/Partisan-SMS/releases/tag/v4.0.0
