### ISSUE TITLE
Pictures sent over MMS disappear in chat thread

### ISSUE THREAD

**Issue by BalooRJ1** [wrwrabbit/Partisan-SMS#43]
### DESCRIPTION
Received pictures in app disappear and reappear when browsing chat threads. Not sure what is causing this.

### STEPS
1. Simply receive a message. It will disappear, then scrolling through prior messages will make it reappear.

### EXPECTED
Pictures are supposed to simply stay present.

**Comment by chancecardona** [comment]
I also have this issue. Is this repo still being maintained / any developments on this?

**Comment by vivabelarus** [comment]
Fixed in 4.0.0.
https://github.com/wrwrabbit/Partisan-SMS/releases/tag/v4.0.0
