### ISSUE TITLE
App crashes after syncing with native sms database

### ISSUE THREAD

**Issue by Mhowser** [wrwrabbit/Partisan-SMS#44]
### DESCRIPTION
The app crashes after syncing from the native android SMS database. I only used qksms 3.9.4 previously.
I'm using android 10 with a Motorola Moto e (ginna)

### STEPS
1. Install latest version
2. Set p-sms as default 
3. Wait for sync to complete
4. App crashes

### EXPECTED 
the app should sync and operate successfully

### OBSERVATIONS
The app becomes blank and unresponsive, then crashes abruptly. Any attempt to open app after gives the same result.

Can you release a version with debugging enabled?

**Comment by vivabelarus** [comment]
Sorry for the long absence of a problem. Please see if the problem persists in the new version of the application: https://github.com/wrwrabbit/Partisan-SMS/releases/tag/v4.0.0. If necessary, we will provide you with a debug version.

**Comment by Mhowser** [comment]
@vivabelarus the update seems to have fixed this issue! Thank you very much!
