### ISSUE TITLE
Submit app to Google Play Store

### ISSUE THREAD

**Issue by Loidauk** [wrwrabbit/Partisan-SMS#45]
### DESCRIPTION
Hi,

Will you make this app available on Google Play Store, to spread the possibilties  to download it.

**Comment by davidangel** [comment]
Or F-Droid?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/wrwrabbit/Partisan-SMS/issues/45#issuecomment-1325925843

@davidangel, https://github.com/wrwrabbit/Partisan-SMS/issues/34#issue-1408313394
