### ISSUE TITLE
Trying to restore backups crashes the app

### ISSUE THREAD

**Issue by AlecHCodes** [wrwrabbit/Partisan-SMS#48]
### DESCRIPTION
Attempting to use the "Backup and restore" function of the app with any file in the "/QKSMS/Backups/" folder crashes the app

### STEPS
1. Move an SMS backup (or any file) to the automatically created "/QKSMS/Backups/" folder
2. Open the app and select the "Backup and restore" option in the hamburger menu

### EXPECTED
App opens the "Backup and restore" menu, allowing backup restoration

### OBSERVATIONS
App crashes

**Comment by vivabelarus** [comment]
Fixed in 4.0.0.
https://github.com/wrwrabbit/Partisan-SMS/releases/tag/v4.0.0
